services:
  - type: worker
    name: youtube-relay-worker
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    startCommand: python3 stream.py
    envVars:
      - key: STREAM_KEY
        value: your_actual_youtube_stream_key
      - key: PLAYLIST_ID
        value: your_actual_playlist_id
