services:
  - type: worker
    name: youtube-relay-worker
    env: docker
    region: oregon  # اختر أقرب منطقة جغرافية لك
    plan: starter  # يمكنك تغييرها حسب الحاجة
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: STREAM_KEY
        value: your_youtube_stream_key
      - key: PLAYLIST_ID
